name: tark_openai_whisper_poc
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  provider: ^6.0.4
  intl: ^0.19.0
  equatable: ^2.0.5
  dio: ^4.0.6
  flutter_secure_storage: ^9.2.2
  json_annotation: ^4.7.0
  build_runner: ^2.3.2
  screenshot: ^2.1.0
  flutter_svg: ^1.1.5
  syncfusion_flutter_datepicker: ^20.3.50
  flutter_multi_formatter: ^2.8.0
  flutter_keyboard_visibility: ^6.0.0
  font_awesome_flutter: ^10.2.1
  dots_indicator: ^2.1.0
  currency_text_input_formatter: ^2.1.7
  pull_to_refresh: ^2.0.0
  camera: ^0.10.5+5
  animated_text_kit: ^4.2.2
  credit_card_type_detector: ^3.0.0
  qr_flutter: ^4.1.0
  uid: ^0.0.2
  url_launcher: ^6.1.6
  dotted_border: ^2.0.0+2
  pin_code_fields: ^7.4.0
  flutter_dotenv: ^5.0.2
  credit_card_validator: ^2.1.0
  package_info_plus: ^4.0.1
  shimmer: ^2.0.0
  easy_localization: ^3.0.1
  permission_handler: ^11.0.1
  bugsnag_flutter: ^3.0.0
  avatar_glow: ^2.0.2
  ndef: ^0.3.1
  translit: ^2.0.1
  collection: ^1.17.1
  share_plus: ^7.1.0
  smooth_page_indicator: ^1.2.0+3
  dart_openai: ^5.1.0
  flutter_sound: ^9.15.54
  path_provider: ^2.0.11
  audioplayers: ^6.0.0
  record: ^5.1.2
  flutter_audio_waveforms: ^1.2.1+8
  translator: ^1.0.0
  noise_meter: ^5.0.2
  ffmpeg_kit_flutter: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: any
  flutter_launcher_icons: ^0.9.2
  lint: ^2.0.0

dependency_overrides:
  http: ^1.1.0
  js: ^0.7.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
