name: geolocation_poc
description: Geolocation POC

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  intl: ^0.19.0
  equatable: ^2.0.5
  dio: ^5.6.0
  flutter_secure_storage: ^9.2.2
  json_annotation: ^4.9.0
  build_runner: ^2.4.12
  flutter_svg: ^2.0.10+1
  flutter_multi_formatter: ^2.13.0
  flutter_keyboard_visibility: ^6.0.0
  font_awesome_flutter: ^10.7.0
  dots_indicator: ^3.0.0
  currency_text_input_formatter: ^2.2.3
  uuid: ^4.4.2
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  url_launcher: ^6.3.0
  pin_code_fields: ^8.0.1
  flutter_dotenv: ^5.1.0
  package_info_plus: ^8.0.2
  shimmer: ^3.0.0
  easy_localization: ^3.0.7
  permission_handler: ^11.3.1
  map_launcher: ^3.5.0
  collection: ^1.18.0
  path_provider: ^2.1.4
  geolocator: ^13.0.1
  location: ^6.0.2
  audioplayers: ^6.1.0
  flutter_background_geolocation: ^4.16.0
  flutter_local_notifications: ^17.2.2
  audio_service: ^0.18.15
  slider_button: ^2.1.0
  wakelock_plus: ^1.2.8
  flutter_compass: ^0.8.0



dev_dependencies:
  flutter_lints: ^2.0.0
  json_serializable: any
  flutter_launcher_icons: ^0.13.1
  lint: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon_cool.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/icon_cool.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/icon_cool.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon_cool.png"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon_cool.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/audio/

  fonts:
    - family: Graphik
      fonts:
        - asset: fonts/GraphikThin.otf
          weight: 100
        - asset: fonts/GraphikExtraLight.otf
          weight: 200
        - asset: fonts/GraphikLight.otf
          weight: 300
        - asset: fonts/GraphikRegular.otf
          weight: 400
        - asset: fonts/GraphikMedium.otf
          weight: 500
        - asset: fonts/GraphikSemiBold.otf
          weight: 600
        - asset: fonts/GraphikBold.otf
          weight: 700
        - asset: fonts/GraphikBlack.otf
          weight: 800
        - asset: fonts/GraphikSuper.otf
          weight: 900
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Light.ttf
          weight: 300
        - asset: fonts/Rubik-Regular.ttf
          weight: 400
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
        - asset: fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: fonts/Rubik-Bold.ttf
          weight: 700
        - asset: fonts/Rubik-ExtraBold.ttf
          weight: 800
        - asset: fonts/Rubik-Black.ttf
          weight: 900
