name: Flutter iOS CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.2'  

    - name: Install dependencies
      run: flutter pub get

    - name: Install CocoaPods dependencies
      run: |
        cd ios
        pod install

    - name: Run tests
      run: flutter test

    - name: Build iOS
      run: flutter build ios --release --no-codesign

    - name: Archive iOS
      run: |
        xcodebuild -workspace ios/Runner.xcworkspace \
          -scheme Runner \
          -sdk iphoneos \
          -configuration Release \
          archive \
          -archivePath $PWD/build/Runner.xcarchive \
          CODE_SIGNING_ALLOWED=NO

    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
          -archivePath $PWD/build/Runner.xcarchive \
          -exportOptionsPlist ios/ExportOptions.plist \
          -exportPath $PWD/build

    - name: Upload to TestFlight
      env:
        APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
        APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
      run: |
        xcrun altool --upload-app --type ios -f build/Runner.ipa \
          --apiKey $APP_STORE_CONNECT_API_KEY_ID \
          --apiIssuer $APP_STORE_CONNECT_API_ISSUER_ID \
          --apiKeyPath $APP_STORE_CONNECT_API_KEY
